USER_NAME: Aya_Mohamed_Local
ID: 55_12084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/task03db
    username: postgres
    password: postgres
    hikari:
      initializationFailTimeout: 0
      connectionTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCBzaWduaW5n
  expiration: 3600000

server:
  port: 8080